version: "3.8"

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=frances
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=Pro_Soft
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "frances@allen.es"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports:
      - "80:80"
    depends_on:
      - postgres 